import { BadRequestException, Body, Controller, Delete, Get, Param, Patch, Post, Req, UseGuards, UseInterceptors } from '@nestjs/common';
import { z } from 'zod';
import { AuthGuard } from '../common/guards/auth.guard';
import { ScopedRequest, UserScopeInterceptor } from '../common/interceptors/user-scope.interceptor';
import { HomeMaintenanceService } from './home-maintenance.service';
const date = z.string().date().nullable().optional(); const amount = z.string().regex(/^\d+(\.\d+)?$/).nullable().optional();
const asset = z.object({ name: z.string().trim().min(1).max(120), type: z.string().trim().min(1).max(80), installedAt: date, expectedLifespanYears: z.number().int().positive().max(100).nullable().optional(), replacementCost: amount, notes: z.string().trim().max(1000).nullable().optional() });
const task = z.object({ homeAssetId: z.string().uuid().nullable().optional(), name: z.string().trim().min(1).max(120), dueDate: date, completedAt: date, estimatedCost: amount, actualCost: amount, notes: z.string().trim().max(1000).nullable().optional() });
@Controller('home-maintenance') @UseGuards(AuthGuard) @UseInterceptors(UserScopeInterceptor)
export class HomeMaintenanceController { constructor(private readonly service: HomeMaintenanceService) {} @Get() list(@Req() req: ScopedRequest) { return this.service.list(req.userId!); } @Get('tasks') tasks(@Req() req: ScopedRequest) { return this.service.listTasks(req.userId!); } @Post('assets') createAsset(@Req() req: ScopedRequest, @Body() body: unknown) { const parsed = asset.safeParse(body); if (!parsed.success) throw new BadRequestException(parsed.error.flatten().fieldErrors); return this.service.createAsset(req.userId!, parsed.data); } @Patch('assets/:id') updateAsset(@Req() req: ScopedRequest, @Param('id') id: string, @Body() body: unknown) { const parsed = asset.partial().extend({ isActive: z.boolean().optional() }).safeParse(body); if (!parsed.success) throw new BadRequestException(parsed.error.flatten().fieldErrors); return this.service.updateAsset(req.userId!, id, parsed.data); } @Delete('assets/:id') removeAsset(@Req() req: ScopedRequest, @Param('id') id: string) { return this.service.removeAsset(req.userId!, id); } @Post('tasks') createTask(@Req() req: ScopedRequest, @Body() body: unknown) { const parsed = task.safeParse(body); if (!parsed.success) throw new BadRequestException(parsed.error.flatten().fieldErrors); return this.service.createTask(req.userId!, parsed.data); } @Patch('tasks/:id') updateTask(@Req() req: ScopedRequest, @Param('id') id: string, @Body() body: unknown) { const parsed = task.partial().safeParse(body); if (!parsed.success) throw new BadRequestException(parsed.error.flatten().fieldErrors); return this.service.updateTask(req.userId!, id, parsed.data); } @Delete('tasks/:id') removeTask(@Req() req: ScopedRequest, @Param('id') id: string) { return this.service.removeTask(req.userId!, id); } }
