import { BadRequestException, Controller, Delete, Get, HttpCode, HttpStatus, Param, Patch, Post, Req, UseGuards, UseInterceptors } from '@nestjs/common';
import { z } from 'zod';
import { AuthGuard } from '../common/guards/auth.guard';
import { ScopedRequest, UserScopeInterceptor } from '../common/interceptors/user-scope.interceptor';
import { IncomeSourcesService } from './income-sources.service';
const money = z.string().regex(/^\d+(\.\d+)?$/);
const createSchema = z.object({ name: z.string().trim().min(1).max(100), kind: z.enum(['EMPLOYMENT', 'SELF_EMPLOYMENT', 'BENEFIT', 'SUPPORT', 'OTHER']).optional(), frequency: z.enum(['WEEKLY', 'BIWEEKLY', 'SEMI_MONTHLY', 'MONTHLY', 'CUSTOM']), expectedNetAmount: money.optional(), nextExpectedDate: z.string().date().optional(), reviewDate: z.string().date().optional(), notes: z.string().trim().max(1000).optional() });
const updateSchema = createSchema.partial().extend({ expectedNetAmount: money.nullable().optional(), nextExpectedDate: z.string().date().nullable().optional(), reviewDate: z.string().date().nullable().optional(), notes: z.string().trim().max(1000).nullable().optional(), isActive: z.boolean().optional() });
@Controller('income-sources') @UseGuards(AuthGuard) @UseInterceptors(UserScopeInterceptor)
export class IncomeSourcesController { constructor(private readonly incomeSources: IncomeSourcesService) {} @Get() list(@Req() req: ScopedRequest) { return this.incomeSources.list(req.userId!); } @Post() create(@Req() req: ScopedRequest) { const parsed = createSchema.safeParse(req.body); if (!parsed.success) throw new BadRequestException(parsed.error.flatten().fieldErrors); return this.incomeSources.create(req.userId!, parsed.data); } @Patch(':id') update(@Req() req: ScopedRequest, @Param('id') id: string) { const parsed = updateSchema.safeParse(req.body); if (!parsed.success) throw new BadRequestException(parsed.error.flatten().fieldErrors); return this.incomeSources.update(req.userId!, id, parsed.data); } @Delete(':id') @HttpCode(HttpStatus.NO_CONTENT) remove(@Req() req: ScopedRequest, @Param('id') id: string) { return this.incomeSources.remove(req.userId!, id); } }
